

solutions = [
  %{
  name: "Clean water facility",
  description: "A clean water system that is localized. This simple solution ease the access to water supply",
  low_capital_input: 2,
  middle_capital_input: 4,
  high_capital_input: 8,
  low_return: 12,
  middle_return: 20,
  high_return: 28,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Nation-wide water supply system",
  description: "Although the system is more expensive, this allows your population to enjoy fresh water by twisting a tap from any where in your country. Water grids are carefully desgned by civil engineers.",
  low_capital_input: 5,
  middle_capital_input: 7,
  high_capital_input: 15,
  low_return: 20,
  middle_return: 25,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Basic clinics around the nation",
  description: "Basic clinics allows your population to be vaccinated and get treated for daily sickness such as cold and fractures",
  low_capital_input: 2,
  middle_capital_input: 4,
  high_capital_input: 8,
  low_return: 12,
  middle_return: 20,
  high_return: 28,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Hospitals with advanced health care",
  description: "More technologically advanced health care provider. This system allows your popukation to get a treatments for cold to cancer. This will significantly improve your nation's standard of living.",
  low_capital_input: 5,
  middle_capital_input: 7,
  high_capital_input: 15,
  low_return: 20,
  middle_return: 25,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Basic Education system",
  description: "Just like Teragoya in old Japan, local small scale education facilities that teaches basic math, literature and science",
  low_capital_input: 2,
  middle_capital_input: 4,
  high_capital_input: 8,
  low_return: 12,
  middle_return: 20,
  high_return: 28,
  roi_func: nil,
  co2_effect: 0,
  is_choice: true,
  comment: "Give a choice to the campers between \"High skilled labour force\", \"Economist\" or \"Engineer\"",
  deleted_at: nil
},
  %{
  name: "Online education system with a usage of AI",
  description: "Any where in your country, your future generation has an access to your high level education. Each students receives a personalized curriculam to empower their natural talent and encourages learning",
  low_capital_input: 6,
  middle_capital_input: 10,
  high_capital_input: 15,
  low_return: 15,
  middle_return: 25,
  high_return: 40,
  roi_func: nil,
  co2_effect: 0,
  is_choice: true,
  comment: "If they chose \"High skilled labour force\" then substitued it for all their \"Youthful Popuation\" card",
  deleted_at: nil
},
  %{
  name: "Coal-powered electricity plant",
  description: "Cheap affordable way to solve your energy crisis. Although this may emmit CO2, affordable electricy would drastically increases your production and your nation's growth.",
  low_capital_input: 3,
  middle_capital_input: 5,
  high_capital_input: 12,
  low_return: 14,
  middle_return: 22,
  high_return: 30,
  roi_func: nil,
  co2_effect: 4,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Renewable Energy",
  description: "Clean energy source, harvested from nature. Although the cost is high, it is unharmful to the enviroment. Hence, allows your nation to have a sustainable growth.",
  low_capital_input: 10,
  middle_capital_input: 14,
  high_capital_input: 18,
  low_return: 14,
  middle_return: 22,
  high_return: 30,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Nuclar FUSION plant",
  description: "Through your investment into research and development, your nation now can enjoy high efficincy nuclear fussion plant. It is safer then the current fission technology and unlike that one, this one does not give out any nuclear waste",
  low_capital_input: 12,
  middle_capital_input: 15,
  high_capital_input: 20,
  low_return: 16,
  middle_return: 24,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Affordable housing",
  description: "With great city desiging, instead of dence and dengerous housing, your population now enojoys new housing with great hope and better standard of living.CO2 still remains due to commuting and less efficient house holds.",
  low_capital_input: 10,
  middle_capital_input: 14,
  high_capital_input: 18,
  low_return: 15,
  middle_return: 25,
  high_return: 30,
  roi_func: nil,
  co2_effect: 2,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Metropolitan",
  description: "With a correctly implimented economic policies and carefully designed city plans, major cities now have a larger and more productive city. There are less crimes due to higher income; public welfare is well proivied; the standards of living is very high.",
  low_capital_input: 12,
  middle_capital_input: 18,
  high_capital_input: 22,
  low_return: 18,
  middle_return: 29,
  high_return: 33,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Metropolitan",
  description: "With a correctly implimented economic policies and carefully designed city plans, major cities now have a larger and more productive city. There are less crimes due to higher income; public welfare is well proivied; the standards of living is very high.",
  low_capital_input: 12,
  middle_capital_input: 18,
  high_capital_input: 22,
  low_return: 16,
  middle_return: 24,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Hospitals with advanced health care",
  description: "More technologically advanced health care provider. This system allows your popukation to get a treatments for cold to cancer. This will significantly improve your nation's standard of living.",
  low_capital_input: 9,
  middle_capital_input: 11,
  high_capital_input: 15,
  low_return: 16,
  middle_return: 24,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Immigration",
  description: "Your nation has welcomed young population from overseas.  business and the economy is thriving with a low labour cost.",
  low_capital_input: 5,
  middle_capital_input: 10,
  high_capital_input: 15,
  low_return: 10,
  middle_return: 15,
  high_return: 20,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Automation",
  description: "With robots and AI technologies,your nation achived high productivity.",
  low_capital_input: 10,
  middle_capital_input: 15,
  high_capital_input: 25,
  low_return: 20,
  middle_return: 35,
  high_return: 40,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Affordable public transport",
  description: "Reduce your commuting time! This allows your cities to be scttered. Designed by civil engineers and supported by the economist. It is cheap and quick, it produces CO2.",
  low_capital_input: 10,
  middle_capital_input: 15,
  high_capital_input: 25,
  low_return: 15,
  middle_return: 30,
  high_return: 40,
  roi_func: nil,
  co2_effect: 2,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Efficient public transport",
  description: "Engineers have created a revolutionally public transport. People enjoy faster and cleaner commuting.",
  low_capital_input: 15,
  middle_capital_input: 18,
  high_capital_input: 28,
  low_return: 17,
  middle_return: 25,
  high_return: 40,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "High Efficincy coal-powered electricity plant",
  description: "Engineers were able to harvest more energy from a single source. This has significantly reduced the carbon emition.",
  low_capital_input: 2,
  middle_capital_input: 3,
  high_capital_input: 12,
  low_return: 18,
  middle_return: 24,
  high_return: 30,
  roi_func: nil,
  co2_effect: 1,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Renewable Energy",
  description: "Clean energy source, harvested from nature. Requires a new sort of Energy plants.  Although the cost is high, it is unharmful to the enviroment. Hence, allows your nation to have a sustainable growth.",
  low_capital_input: 10,
  middle_capital_input: 14,
  high_capital_input: 18,
  low_return: 14,
  middle_return: 22,
  high_return: 30,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},
  %{
  name: "Nuclar FUSION plant",
  description: "Through your investment into research and development, your nation now can enjoy high efficincy nuclear fussion plant. It is safer then the current fission technology and unlike that one, this one does not give out any nuclear waste",
  low_capital_input: 12,
  middle_capital_input: 15,
  high_capital_input: 20,
  low_return: 16,
  middle_return: 24,
  high_return: 36,
  roi_func: nil,
  co2_effect: 0,
  is_choice: false,
  comment: nil,
  deleted_at: nil
},

]

for solution <- solutions do
  {:ok, _} = Planet.Cosmos.create_solution(solution)
end
